#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidServiceReader.Resource", IsApplication=true)]

namespace AndroidServiceReader
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_dirt = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_dirt_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_dirt_unselected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_is = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_is_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_is_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sno = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_sno_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_sno_unselected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_vann = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_vann_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_vann_unselected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int monoandroidsplash = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AvalancheScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int monoandroidsplash = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
